# Generated by Django 5.2.1 on 2025-06-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
