# Generated by Django 5.2.1 on 2025-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='view_count',
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
